### ISSUE TITLE
js - unresolved imports an external dependecies

### ISSUE THREAD

**Issue by quarkus** [webtides/tasks#4]
We should discuss wether unresolved dependencies should be treated as external deps by default.

I think the build should rather crash insteadof warn silently.

**Comment by eddyloewen** [comment]
I think we already discussed this, no?
We agreed that unresolved dependencies should NOT be treated as external dependencies by default and that the build should rather crash!

The problem was only that there is no such option for rollup... We should probably create an issue on the rollupjs repo and try to ask nicely for such an option maybe?

**Comment by eddyloewen** [comment]
@quarkus I finally found a way to make the rollup build crash for unresolved dependecies: https://rollupjs.org/guide/en/#onwarn

Should I make this the default for our rollup task? Or only enable it via feature flag?

**Comment by quarkus** [comment]
I think it would be great to have an option but it should crash by default.
